Controllers/AchievementController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ThatsLife.Models;
using ThatsLife.Models.DAL;
using ThatsLife.Models.Entity;
using ThatsLife.Models.ViewModels;

namespace ThatsLife.Controllers
{
    public class AchievementController : Controller
    {
        private readonly IRepository<PlayerProfile> _profileRepository;
        private readonly IRepository<PlayerPrestigeScore> _prestigeScoreRepository;
        public AchievementController(IRepository<PlayerProfile> profileRepository, 
            IRepository<PlayerPrestigeScore> prestigeScoreRepository)
        {
            _profileRepository = profileRepository;
            _prestigeScoreRepository = prestigeScoreRepository;
        }
        
        public IActionResult Leaderboard()
        {

            var leaderBoardViewModel = new LeaderBoardViewModel();
            //List<int?> profiles = _prestigeScoreRepository.FindAll().Select(p => p.ProfileId).Distinct().ToList();
            var innerJoin = _prestigeScoreRepository.FindAll()
                .Join(_profileRepository.FindAll(),
                playerScore => playerScore.ProfileId,
                playerProfile => playerProfile.Id,
                (playerScore, playerProfile) => new
                {
                    profileName = playerProfile.ProfileName,
                    pointsEarned = playerScore.PointsEarned,
                    totalScore = playerScore.Score,
                    source = playerScore.Source,
                    createDate = playerScore.CreatedDate
                }).GroupBy(p => new { p.profileName, p.source }).Select(group => new
                {
                    group.Key.profileName,
                    score = group.Max(d => d.totalScore)

                }).OrderByDescending(s => s.score).Select(s => new
                {
                    s.profileName,
                    s.score
                }).GroupBy(p => p.profileName).Select(s => new
                {
                    profileName = s.Key,
                    score = s.Max(m => m.score)
                }).OrderByDescending(o => o.score).ToList();

            List<PlayerRanking> playerRankings = new List<PlayerRanking>();
            foreach(var item in innerJoin)
            {
                PlayerRanking ranking = new PlayerRanking();
                ranking.ProfileName = item.profileName;
                ranking.Score = item.score;
                playerRankings.Add(ranking);
            }
            
            return View(playerRankings);
        }
    }
}

Controllers/StockController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ThatsLife.Models;
using ThatsLife.Models.DAL;
using ThatsLife.Models.Entity;
using ThatsLife.Models.ViewModels;

namespace ThatsLife.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IRepository<PlayerProfile> _ProfileRepository;
        private readonly IRepository<PlayerStock> _stockRepository;
        private readonly IRepository<PlayerTransaction> _transactionRepository;
        private readonly IRepository<PlayerPrestigeScore> _prestigescoreRepository;
        private readonly IRepository<PlayerCash> _cashRepository;
        private readonly IConfiguration _configuration;
        private string _url;
        private string _iexcloudKey;

        public StockController(SignInManager<IdentityUser> signInManager,
                       UserManager<IdentityUser> userManager,
                       IRepository<PlayerProfile> profileRepository,
                       IRepository<PlayerStock> stockRepository,
                       IRepository<PlayerTransaction> transactionRepository,
                       IRepository<PlayerPrestigeScore> prestigescoreRepository,
                       IRepository<PlayerCash> cashRepository,
                       IConfiguration configuration)
        {
            _userManager = userManager;
            _ProfileRepository = profileRepository;
            _stockRepository = stockRepository;
            _transactionRepository = transactionRepository;
            _prestigescoreRepository = prestigescoreRepository;
            _cashRepository = cashRepository;
            _configuration = configuration;
            _iexcloudKey = _configuration["APIs:IExapix"];
        }


        public async Task<IActionResult> StockQuoteAsync(string symbol)
        {

            var userId = _userManager.GetUserId(User);
            PlayerProfile player = _ProfileRepository.FindByCondition(p => p.UserId == userId).First();

            StockQuoteViewModel stockQuoteViewModel = new StockQuoteViewModel();
            stockQuoteViewModel.Player = player;

            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Ignore
            };

            _url = $"https://cloud.iexapis.com/stable/stock/{symbol}/quote?token={_iexcloudKey}";
            var json = await ApiHub.GetJson(_url);
            StockQuote stockQuote = JsonConvert.DeserializeObject<StockQuote>(json,settings);
            stockQuoteViewModel.StockQuote = stockQuote;

            _url = $"https://cloud.iexapis.com/stable/stock/{symbol}/logo?token={_iexcloudKey}";
            json = await ApiHub.GetJson(_url);
            JObject obj = JObject.Parse(json);
            string logoUrl = (string)obj["url"];
            stockQuoteViewModel.LogoUrl = logoUrl;

            _url = $"https://cloud.iexapis.com/stable/stock/{symbol}/company?token={_iexcloudKey}";
            json = await ApiHub.GetJson(_url);
            stockQuoteViewModel.Company = JsonConvert.DeserializeObject<Company>(json,settings);

            return View("StockQuote", stockQuoteViewModel);
        }

        /// <summary>
        /// Once Order has been confirmed this endpoint will handle the transaction of
        /// updating players balance and add to player's stocks.  Prestige score
        /// is calculted with the weighted value coming from the P/E Ratio.
        /// </summary>
        /// <param name="symbol"></param>
        /// <param name="playerId"></param>
        /// <param name="price"></param>
        /// <param name="shares"></param>
        /// <param name="peRatio"></param>
        /// <returns></returns>
        public IActionResult Buy(string symbol, string price, string shares, string peRatio)
        {

            decimal _price = decimal.Parse(price);
            int _shares = int.Parse(shares);
            decimal _peRatio = decimal.Parse(peRatio?? "0");
            decimal total = _price * _shares;

            var userId = _userManager.GetUserId(User);
            PlayerProfile player = _ProfileRepository.FindByCondition(p => p.UserId == userId).First();

            PlayerCash playerCash = new PlayerCash();
            playerCash.ProfileId = player.Id;
            playerCash.Balance = _cashRepository
               .FindByCondition(p => p.ProfileId == player.Id)
               .OrderByDescending(c => c.CreatedDate)
               .Select(p => p.Balance)
               .FirstOrDefault();

            //verfiy player has enough currency to purchase order
            if (total > playerCash.Balance)
            {
                return View("InsufficentFundsView", total);
            }
            else
            {
                PlayerStock PlayerStock = new PlayerStock();
                PlayerStock.StockSymbol = symbol;
                PlayerStock.ProfileId = player.Id;
                PlayerStock.PurchasePrice = _price;
                PlayerStock.Shares = _shares;
                _stockRepository.Create(PlayerStock);

                playerCash.Balance -= total;
                _cashRepository.Create(playerCash);

                PlayerTransaction playerTransaction = new PlayerTransaction();
                playerTransaction.ProfileId = player.Id;
                playerTransaction.TransactionType = "Buy";
                playerTransaction.TransactionDescription = $"{symbol} Purchased";
                playerTransaction.Quantity = _shares;
                playerTransaction.Price = total;
                _transactionRepository.Create(playerTransaction);

                //prestige score is based on P/E Ratio. 
                PlayerPrestigeScore playerPrestige = new PlayerPrestigeScore();
                playerPrestige.ProfileId = player.Id;
                playerPrestige.Source = "Risk Reward";
                playerPrestige.Score = _prestigescoreRepository
                .FindByCondition(p => p.ProfileId == player.Id)
                .OrderByDescending(c => c.CreatedDate)
                .Select(p => p.Score)
                .FirstOrDefault();
                decimal purchaseToPlayerBalanceRatio = total / playerCash.Balance;  //how vested the player is in this stock
                decimal stockValue = 1000 - _peRatio;  //lower P/E Ratio means stock is more valuable
                playerPrestige.Score += (int)(stockValue * purchaseToPlayerBalanceRatio);
                playerPrestige.PointsEarned = (int)(stockValue * purchaseToPlayerBalanceRatio);
                _prestigescoreRepository.Create(playerPrestige);
            }

           
            
            return RedirectToAction("Portfolio", "stock");
        }

        public IActionResult Sell(string stockId, string value)
        {
            var userId = _userManager.GetUserId(User);
            PlayerProfile player = _ProfileRepository.FindByCondition(p => p.UserId == userId).FirstOrDefault();


            PlayerStock playerStock = _stockRepository.FindByCondition(s => s.Id == int.Parse(stockId)).FirstOrDefault();
            _stockRepository.Delete(playerStock);


            PlayerCash playerCash = new PlayerCash();
            playerCash.ProfileId = player.Id;
            decimal marketValue = decimal.Parse(value);
            playerCash.Balance = _cashRepository
               .FindByCondition(p => p.ProfileId == player.Id)
               .OrderByDescending(c => c.CreatedDate)
               .Select(p => p.Balance)
               .FirstOrDefault();
            playerCash.Balance += marketValue;
            _cashRepository.Create(playerCash);


            string symbol = playerStock.StockSymbol;
            int shares = playerStock.Shares;
            decimal totalCost = (shares * playerStock.PurchasePrice);

            PlayerTransaction playerTransaction = new PlayerTransaction();
            playerTransaction.ProfileId = player.Id;
            playerTransaction.TransactionType = "Sell";
            playerTransaction.TransactionDescription = $"{symbol} Purchased";
            playerTransaction.Quantity = shares;
            playerTransaction.Price = marketValue;
            _transactionRepository.Create(playerTransaction);


            PlayerPrestigeScore playerPrestige = new PlayerPrestigeScore();
            playerPrestige.ProfileId = player.Id;
            playerPrestige.Source = "Profit Reward";
            decimal stockReturn = marketValue - totalCost;
            playerPrestige.Score = _prestigescoreRepository
                .FindByCondition(p => p.ProfileId == player.Id)
                .OrderByDescending(c => c.CreatedDate)
                .Select(p => p.Score)
                .FirstOrDefault();
            if (stockReturn > 0)
            {
                playerPrestige.Score += (int)stockReturn;
                playerPrestige.PointsEarned = (int)stockReturn;
            }
            _prestigescoreRepository.Create(playerPrestige);


           
            _stockRepository.Delete(playerStock);
 
            return RedirectToAction("Portfolio");
        }

        public async Task<IActionResult> PortfolioAsync()
        {
            var userId = _userManager.GetUserId(User);

            //Retrieves data from database
            StockPortfolioViewModel stockPortfolioViewModel = new StockPortfolioViewModel();
            PlayerProfile player = _ProfileRepository.FindByCondition(p => p.UserId == userId).First();
            stockPortfolioViewModel.PlayProfile = player;
            IEnumerable<PlayerStock> playerStocks = _stockRepository.FindByCondition(p => p.ProfileId == player.Id);

Views/Shared/Components/Player/PlayerViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ThatsLife.Models;
using ThatsLife.Models.DAL;
using ThatsLife.Models.Entity;
using ThatsLife.Models.ViewModels;

namespace ThatsLife.Views.Shared.Components.Player
{
    public class PlayerViewComponent : ViewComponent
    {

        private readonly IRepository<PlayerProfile> _profileRepository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IRepository<PlayerCash> _cashRepository;
        private readonly IRepository<PlayerPrestigeScore> _prestigescoreRepository;

        public PlayerViewComponent(IRepository<PlayerProfile> profileRepository,
            UserManager<IdentityUser> userManager,
            IRepository<PlayerCash> cashRepository,
            IRepository<PlayerPrestigeScore> prestigescoreRepository)

        {
            _profileRepository = profileRepository;
            _cashRepository = cashRepository;
            _prestigescoreRepository = prestigescoreRepository;
            _userManager = userManager;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            PlayerProfile player = _profileRepository.FindByCondition(p => p.UserId == user.Id).First();
            PlayerViewModel playerViewModel = new PlayerViewModel();
            
            playerViewModel.ProfileName = player.ProfileName;
            playerViewModel.Score = _prestigescoreRepository
                .FindByCondition(p => p.ProfileId == player.Id)
                .OrderByDescending(c => c.CreatedDate)
                .Select(p => p.Score)
                .FirstOrDefault();
            playerViewModel.Cash = _cashRepository
               .FindByCondition(p => p.ProfileId == player.Id)
               .OrderByDescending(c => c.CreatedDate)
               .Select(p => p.Balance)
               .FirstOrDefault();
            return View("Default", playerViewModel );
        }
    }
}

Views/Shared/Components/Ticker/TickerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using ThatsLife.Models;

namespace ThatsLife.Views.Shared.Components
{
    /// <summary>
    /// This component provide stock ticker information of top tech stocks
    /// using IExloud's API and deserializes it to the StockQuote Model
    /// </summary>
    public class TickerViewComponent: ViewComponent
    {
        private string _URL;
        private string _IExcloudKey;

        public IConfiguration Configuration { get; }
        public TickerViewComponent(IConfiguration configuration)
        {
            Configuration = configuration;
            _IExcloudKey = Configuration["APIs:IExapix"];
            _URL = $"https://cloud.iexapis.com/stable/stock/market/batch/?symbols=,googl,aapl,fb,msft,amzn,nflx,tsla,intc&types=quote&token={_IExcloudKey}";
        }
        /// <summary>
        /// Gets Stock information from IExcloud API in form of json object and then
        /// deserializes it into a list of StockQuotes.
        /// </summary>
        /// <returns>List of StockQuotes to the Ticker ViewComponent</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<StockQuote> stocks = new List<StockQuote>();
            var json = await ApiHub.GetJson(_URL);
            var root = JObject.Parse(json);
            foreach (var r in root)
            {
                var sybmol = JsonConvert.DeserializeObject<StockQuote>(r.Value["quote"].ToString());
                stocks.Add(sybmol);
            }
            return View("Default", stocks);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewBag.Title - That's Life</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/jqueryui/jquery-ui.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>




    <img src="~/images/city2.png" class="banner" />
    <nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="#menu-toggle" id="menu-toggle"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sitenav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="sitenav">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item active">
                    <a class="nav-link text-dark font-weight-bolder" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </nav>
    <main>
        @if (SignInManager.IsSignedIn(User))
        {
            <button id="sidebar-toggle" class=" col-1 d-sm-block d-md-block d-lg-none btn btn-group-toggle p-4 ">
                <i class="fas fa-align-left"></i>
            </button>
            <div class="d-flex">
                <partial name="_SideNavigation" />
                <div class="container-fluid">
                    @await Component.InvokeAsync("Ticker")
                    @await Component.InvokeAsync("Player")
                    @RenderBody()
                </div>
            </div>
        }
        @RenderBody()
    </main>
    <footer>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>

        


        $(document).ready(function () {
            $("#sidebar-toggle").on('click', function () {
                $("#sidebar").toggleClass("active");
            });
        });

        function ValidateQuiz() {

            var type = document.getElementById('type');
            var radios = $('input:radio');
            var index = 0;
            var question = 0;

            for (var i = 0; i < radios.length; i++) {
                var radio = radios[i];


                if (type.value == 'multiple') {

                    index = i % 4;
                    question = Math.floor((i / 4) + 1);
                }
                else {
                    index = i % 2;
                    question = Math.floor((i / 2) + 1);
                }

                var icon = document.getElementById('icon-' + question + '-' + index);


                if (radio.value == 'true' && radio.checked == true) {
                    icon.setAttribute("class", "fas fa-check fa-lg text-success ml-5 pr-3");
                }
                else if (radio.value == 'false' && radio.checked == true) {
                    icon.setAttribute("class", "fas fa-times fa-lg text-danger ml-5 pr-3");
                }
            }
            document.getElementById('submit').setAttribute("class", "btn btn-lg btn-secondary mt-5 d-none");
            document.getElementById('continue').setAttribute("class", "btn btn-lg btn-success mt-5");
    }

        function Purchase(peRatio) {
            var symbolValue = document.getElementById("symbol").innerHTML;
            var priceValue = document.getElementById("price").innerHTML;
            var sharesValue = document.getElementById("shares").value;

            window.location.href = '@Url.Action("buy","stock")?symbol=' + symbolValue +
                '&price=' + priceValue +
                '&shares=' + sharesValue+
                '&peRatio=' + peRatio;
        };

        function ConfirmBuy () {
            var priceValue = document.getElementById("price").innerHTML;
            var sharesValue = document.getElementById("shares").value;
            var total = (sharesValue * priceValue).toLocaleString('en-US', {
                style: 'currency',
                currency: 'USD'
            });

            document.getElementById("confirmBuy-modal-shares").innerHTML = sharesValue;
            document.getElementById("confirmBuy-modal-total").innerHTML = total;
            $('#confirmBuy-modal').modal('show')
        }


        function Sell() {
            document.getElementById("sell-form").submit();
        };

    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SideNavigation.cshtml
    <div class="bg-light border-right active" id="sidebar">

        <div class="list-group font-weight-bold">
            <a asp-controller="Stock" asp-action="Exchange" class="list-group-item bg-light list-group-item-action"><i class="fas fa-chart-line fa-2x pr-4 mr-5"></i> Exchange</a>

            <a asp-controller="Stock" asp-action="Portfolio" class="list-group-item bg-light list-group-item-action"><i class="fas fa-money-check-alt fa-2x  pr-4 mr-5"></i>Portfolio</a>

            <a asp-controller="Trivia" asp-action="Parameters" class="list-group-item bg-light list-group-item-action"><i class="fas fa-chalkboard fa-2x pr-4 mr-5"></i>Trivia Questions</a>

            <a asp-controller="Trivia" asp-action="Performance" class="list-group-item bg-light list-group-item-action"><i class="fas fa-chart-pie fa-2x pr-4 mr-5"></i>Trivia Performance</a>

            <a asp-controller="Achievement" asp-action="Portfolio" class="list-group-item  bg-light list-group-item-action"><i class="fas fa-trophy fa-2x pr-4 mr-5"></i>Achievments</a>

            <a asp-controller="Achievement" asp-action="Leaderboard" class="list-group-item bg-light list-group-item-action"><i class="fas fa-list-ol fa-2x pr-4 mr-5"></i>Leaderboard</a>
        </div>
    </div>