Models/StockQuote.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.ComponentModel.DataAnnotations;

namespace ThatsLife.Models
{
    public class StockQuote
    {
        public string Symbol { get; set; }
        public string CompanyName { get; set; }
        public string CalculationPrice { get; set; }
        public float? Open { get; set; }
        public float? High { get; set; }
        public float? Low { get; set; }

        [DisplayFormat(DataFormatString = "c")]
        public decimal LatestPrice { get; set; }

        public long LatestUpdate { get; set; }
        public float? LatestVolume { get; set; }
        public float PreviousClose { get; set; }
        public float? PreviousVolume { get; set; }

        public float Change { get; set; }

        public decimal ChangePercent { get; set; }
        public int AvgTotalVolume { get; set; }
        public long MarketCap { get; set; }
        public float? PeRatio { get; set; }
        public float Week52High { get; set; }
        public float Week52Low { get; set; }
        public float YtdChange { get; set; }
        public bool IsUSMarketOpen { get; set; }
        public DateTime LatesUpdateDT
        {
            get
            {
                return DateTimeOffset.FromUnixTimeMilliseconds(LatestUpdate).LocalDateTime;
            }
        }

    }
}

Models/ViewModels/ExchangeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ThatsLife.Models.Entity;

namespace ThatsLife.Models.ViewModels
{
    public class ExchangeViewModel
    {

        public PlayerProfile profile { get; set; }

       
    }
}

Models/ViewModels/StockQuoteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ThatsLife.Models.Entity;

namespace ThatsLife.Models.ViewModels
{
    public class StockQuoteViewModel
    {
        
        public PlayerProfile Player { get; set; }
        public string LogoUrl { get; set; }
        public StockQuote StockQuote {get;set;}
        public Company Company { get; set; }
        public int Shares { get; set; }

    }
}

Controllers/StockController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ThatsLife.Models;
using ThatsLife.Models.DAL;
using ThatsLife.Models.Entity;
using ThatsLife.Models.ViewModels;

namespace ThatsLife.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IRepository<PlayerProfile> _ProfileRepository;
        private readonly IRepository<PlayerStock> _stockRepository;
        private readonly IRepository<PlayerTransaction> _transactionRepository;
        private readonly IRepository<PlayerPrestigeScore> _prestigescoreRepository;
        private readonly IRepository<PlayerCash> _cashRepository;
        private readonly IConfiguration _configuration;
        private string _url;
        private string _iexcloudKey;

        public StockController(SignInManager<IdentityUser> signInManager,
                       UserManager<IdentityUser> userManager,
                       IRepository<PlayerProfile> profileRepository,
                       IRepository<PlayerStock> stockRepository,
                       IRepository<PlayerTransaction> transactionRepository,
                       IRepository<PlayerPrestigeScore> prestigescoreRepository,
                       IRepository<PlayerCash> cashRepository,
                       IConfiguration configuration)
        {
            _userManager = userManager;
            _ProfileRepository = profileRepository;
            _stockRepository = stockRepository;
            _transactionRepository = transactionRepository;
            _prestigescoreRepository = prestigescoreRepository;
            _cashRepository = cashRepository;
            _configuration = configuration;
            _iexcloudKey = _configuration["APIs:IExapix"];
        }


        public async Task<IActionResult> StockQuoteAsync(string symbol)
        {

            var userId = _userManager.GetUserId(User);
            PlayerProfile player = _ProfileRepository.FindByCondition(p => p.UserId == userId).First();

            StockQuoteViewModel stockQuoteViewModel = new StockQuoteViewModel();
            stockQuoteViewModel.Player = player;

            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Ignore
            };

            _url = $"https://cloud.iexapis.com/stable/stock/{symbol}/quote?token={_iexcloudKey}";
            var json = await ApiHub.GetJson(_url);
            StockQuote stockQuote = JsonConvert.DeserializeObject<StockQuote>(json,settings);
            stockQuoteViewModel.StockQuote = stockQuote;

            _url = $"https://cloud.iexapis.com/stable/stock/{symbol}/logo?token={_iexcloudKey}";
            json = await ApiHub.GetJson(_url);
            JObject obj = JObject.Parse(json);
            string logoUrl = (string)obj["url"];
            stockQuoteViewModel.LogoUrl = logoUrl;

            _url = $"https://cloud.iexapis.com/stable/stock/{symbol}/company?token={_iexcloudKey}";
            json = await ApiHub.GetJson(_url);
            stockQuoteViewModel.Company = JsonConvert.DeserializeObject<Company>(json,settings);

            return View("StockQuote", stockQuoteViewModel);
        }

        /// <summary>
        /// Once Order has been confirmed this endpoint will handle the transaction of
        /// updating players balance and add to player's stocks.  Prestige score
        /// is calculted with the weighted value coming from the P/E Ratio.
        /// </summary>
        /// <param name="symbol"></param>
        /// <param name="playerId"></param>
        /// <param name="price"></param>
        /// <param name="shares"></param>
        /// <param name="peRatio"></param>
        /// <returns></returns>
        public IActionResult Buy(string symbol, string price, string shares, string peRatio)
        {

            decimal _price = decimal.Parse(price);
            int _shares = int.Parse(shares);
            decimal _peRatio = decimal.Parse(peRatio?? "0");
            decimal total = _price * _shares;

            var userId = _userManager.GetUserId(User);
            PlayerProfile player = _ProfileRepository.FindByCondition(p => p.UserId == userId).First();

            PlayerCash playerCash = new PlayerCash();
            playerCash.ProfileId = player.Id;
            playerCash.Balance = _cashRepository
               .FindByCondition(p => p.ProfileId == player.Id)
               .OrderByDescending(c => c.CreatedDate)
               .Select(p => p.Balance)
               .FirstOrDefault();

            //verfiy player has enough currency to purchase order
            if (total > playerCash.Balance)
            {
                return View("InsufficentFundsView", total);
            }
            else
            {
                PlayerStock PlayerStock = new PlayerStock();
                PlayerStock.StockSymbol = symbol;
                PlayerStock.ProfileId = player.Id;
                PlayerStock.PurchasePrice = _price;
                PlayerStock.Shares = _shares;
                _stockRepository.Create(PlayerStock);

                playerCash.Balance -= total;
                _cashRepository.Create(playerCash);

                PlayerTransaction playerTransaction = new PlayerTransaction();
                playerTransaction.ProfileId = player.Id;
                playerTransaction.TransactionType = "Buy";
                playerTransaction.TransactionDescription = $"{symbol} Purchased";
                playerTransaction.Quantity = _shares;
                playerTransaction.Price = total;
                _transactionRepository.Create(playerTransaction);

                //prestige score is based on P/E Ratio. 
                PlayerPrestigeScore playerPrestige = new PlayerPrestigeScore();
                playerPrestige.ProfileId = player.Id;
                playerPrestige.Source = "Risk Reward";
                playerPrestige.Score = _prestigescoreRepository
                .FindByCondition(p => p.ProfileId == player.Id)
                .OrderByDescending(c => c.CreatedDate)
                .Select(p => p.Score)
                .FirstOrDefault();
                decimal purchaseToPlayerBalanceRatio = total / playerCash.Balance;  //how vested the player is in this stock
                decimal stockValue = 1000 - _peRatio;  //lower P/E Ratio means stock is more valuable
                playerPrestige.Score += (int)(stockValue * purchaseToPlayerBalanceRatio);
                playerPrestige.PointsEarned = (int)(stockValue * purchaseToPlayerBalanceRatio);
                _prestigescoreRepository.Create(playerPrestige);
            }

           
            
            return RedirectToAction("Portfolio", "stock");
        }

        public IActionResult Sell(string stockId, string value)
        {
            var userId = _userManager.GetUserId(User);
            PlayerProfile player = _ProfileRepository.FindByCondition(p => p.UserId == userId).FirstOrDefault();


            PlayerStock playerStock = _stockRepository.FindByCondition(s => s.Id == int.Parse(stockId)).FirstOrDefault();
            _stockRepository.Delete(playerStock);


            PlayerCash playerCash = new PlayerCash();
            playerCash.ProfileId = player.Id;
            decimal marketValue = decimal.Parse(value);
            playerCash.Balance = _cashRepository
               .FindByCondition(p => p.ProfileId == player.Id)
               .OrderByDescending(c => c.CreatedDate)
               .Select(p => p.Balance)
               .FirstOrDefault();
            playerCash.Balance += marketValue;
            _cashRepository.Create(playerCash);


            string symbol = playerStock.StockSymbol;
            int shares = playerStock.Shares;
            decimal totalCost = (shares * playerStock.PurchasePrice);

            PlayerTransaction playerTransaction = new PlayerTransaction();
            playerTransaction.ProfileId = player.Id;
            playerTransaction.TransactionType = "Sell";
            playerTransaction.TransactionDescription = $"{symbol} Purchased";
            playerTransaction.Quantity = shares;
            playerTransaction.Price = marketValue;
            _transactionRepository.Create(playerTransaction);


            PlayerPrestigeScore playerPrestige = new PlayerPrestigeScore();
            playerPrestige.ProfileId = player.Id;
            playerPrestige.Source = "Profit Reward";
            decimal stockReturn = marketValue - totalCost;
            playerPrestige.Score = _prestigescoreRepository
                .FindByCondition(p => p.ProfileId == player.Id)
                .OrderByDescending(c => c.CreatedDate)
                .Select(p => p.Score)
                .FirstOrDefault();
            if (stockReturn > 0)
            {
                playerPrestige.Score += (int)stockReturn;
                playerPrestige.PointsEarned = (int)stockReturn;
            }
            _prestigescoreRepository.Create(playerPrestige);


           
            _stockRepository.Delete(playerStock);
 
            return RedirectToAction("Portfolio");
        }

        public async Task<IActionResult> PortfolioAsync()
        {
            var userId = _userManager.GetUserId(User);

            //Retrieves data from database
            StockPortfolioViewModel stockPortfolioViewModel = new StockPortfolioViewModel();
            PlayerProfile player = _ProfileRepository.FindByCondition(p => p.UserId == userId).First();
            stockPortfolioViewModel.PlayProfile = player;
            IEnumerable<PlayerStock> playerStocks = _stockRepository.FindByCondition(p => p.ProfileId == player.Id);

Views/Stock/Components/Decliners/DeclinersViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ThatsLife.Models;

namespace ThatsLife.Views.Stock.Components.Decliners
{
    public class DeclinersViewComponent: ViewComponent
    {
        private string _URL;
        private string _IExcloudKey;

        public IConfiguration Configuration { get; }
        public DeclinersViewComponent(IConfiguration configuration)
        {
            Configuration = configuration;
            _IExcloudKey = Configuration["APIs:IExapix"];
            _URL = $"https://cloud.iexapis.com/stable/stock/market/list/losers?token={_IExcloudKey}";
        }
        /// <summary>
        /// Gets Stock information from IExcloud API in form of json object and then
        /// deserializes it into a list of StockQuotes.
        /// </summary>
        /// <returns>List of StockQuotes to the Ticker ViewComponent</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<StockQuote> stocks = new List<StockQuote>();

            var json = await ApiHub.GetJson(_URL);
            var root = JArray.Parse(json);
            var children = root.Children();
            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Ignore
            };
            foreach (JToken t in children)
            {
                var symbol = JsonConvert.DeserializeObject<StockQuote>(t.ToString(), settings);
                stocks.Add(symbol);
            }
            return View("Default", stocks);
        }
    }
}

Views/Stock/Components/Gainers/GainersViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using ThatsLife.Models;


namespace ThatsLife.Views.Stock.Components.Gainers
{
    public class GainersViewComponent : ViewComponent
    {
        private string _URL;
        private string _IExcloudKey;

        public IConfiguration Configuration { get; }
        public GainersViewComponent(IConfiguration configuration)
        {
            Configuration = configuration;
            _IExcloudKey = Configuration["APIs:IExapix"];
            _URL = $"https://cloud.iexapis.com/stable/stock/market/list/gainers?token={_IExcloudKey}";
        }
        /// <summary>
        /// Gets Stock information from IExcloud API in form of json object and then
        /// deserializes it into a list of StockQuotes.
        /// </summary>
        /// <returns>List of StockQuotes to the Ticker ViewComponent</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<StockQuote> stocks = new List<StockQuote>();

                    var json = await ApiHub.GetJson(_URL);
                    var root = JArray.Parse(json);
                    var children = root.Children();
                    var settings = new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore,
                        MissingMemberHandling = MissingMemberHandling.Ignore
                    };
                    foreach (JToken t in children)
                    {
                        var symbol = JsonConvert.DeserializeObject<StockQuote>(t.ToString(),settings);
                        stocks.Add(symbol);
                    }
            return View("Default", stocks);
        }
    }
}

Views/Stock/Exchange.cshtml
        <!--Displays Heading and inline form to get stock symbol to lookup-->
        <div class="row align-items-center">
            <div class="col-8 ">
                <p class="display-4">
                    Stock Activity
                </p>
                <p class="mb-3 lead">List of Gainers and Decliners are common stocks that have a market cap of at least 200M and a volume of at least 20K</p>
            </div>
            <div class="col-4 ">
                <form asp-action="stockquote" method="post" class="form-inline">
                    <div class="form-group">
                        <input type="text" class="form-control form-control-lg" id="symbol" name="symbol" placeholder="Enter Stock Symbol">
                    </div>
                    <button type="submit" class="btn btn-primary ml-md-3">Get Stock Quote</button>
                </form>
            </div>
        </div>
        
        <!--Provides two regions on exchange that show top 10 gainers and top 10 decliners-->
        <div class="row">
            <div class="col">@await Component.InvokeAsync("Gainers")</div>
            <div class="col"> @await Component.InvokeAsync("Decliners")</div>
        </div>

Views/Stock/InsufficientFunds.cshtml
@model decimal 

<div class="row">
    <div class="col">
        <div class="card" style="width: 36rem; height:36rem">
            <img class="card-img-top" src="..." alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Insufficent Funds</h5>
                <p class="card-text">You don't have enough funds to cover the @Model.ToString("c") purchase.</p>
                <a asp-action="Exchange" asp-controller="stock" class="btn btn-primary">Exit</a>
            </div>
        </div>
    </div>
</div>

Views/Stock/Portfolio.cshtml
@model ThatsLife.Models.ViewModels.StockPortfolioViewModel



    <div class="row m-2 w-100 p-3 ">
  
        <div class="@(Model.TotalTodaysGain > 0 ? "col bg-success text-white shadow mx-2  p-3" : "col bg-danger text-white shadow mx-2 p-3")">
            <div class="row">
                <div class="col">
                    <div class="font-weight-bolder"> @Model.TotalTodaysGain.ToString("c")</div>
                    <div>Performance today</div>
                </div>
                <div class="col font-weight-bolder text-right">
                    @Model.TotalTodaysGainPercent.ToString("p")
                </div>
            </div>
        </div>
        <div class="@(Model.TotalReturn > 0 ? "col ml-2 bg-success text-white shadow mx-2 p-3": "col ml-2 bg-danger text-white shadow mx-2 p-3")">
            <div class="row">
                <div class="col">
                    <div class="font-weight-bolder">@Model.TotalReturn.ToString("c")</div>
                    <div>Overall Return</div>
                </div>
                <div class="col font-weight-bolder text-right">
                    @Model.TotalReturnPercentage.ToString("p")
                </div>
            </div>
        </div>
        <div class="col shadow mx-2 p-3">
            <div class="row">
                <div class="col ">
                    <div class="font-weight-bolder">@Model.TotalStockCost.ToString("c")</div>
                    <div>Portfolio cost</div>
                </div>
            </div>
        </div>
        <div class="col shadow mx-2 p-3">
            <div class="row">
                <div class="col ">
                    <div class="font-weight-bolder">@Model.TotalStockValue.ToString("c")</div>
                    <div>Portfolio value</div>
                </div>
            </div>
        </div>
    </div>

    <div class=" row border shadow m-2 w-100 p-3">

        <div class="col">
            <div><p class="pb-4 h5">My portfolio<p></div>
            <div class="table-responsive-sm">
                <table class="table table-striped">
                    @if (Model.Stocks != null)
                    {
                        <thead>
                            <tr scope="row" class="font-weight-bold">
                                <th>Symbol</th>
                                <th>Name</th>
                                <th scope="col" class="text-right font-weight-bold">Price</th>
                                <th scope="col" class="text-right font-weight-bold">Change</th>
                                <th scope="col" class="text-right font-weight-bold">% Change</th>
                                <th scope="col" class="text-right font-weight-bold">Shares</th>
                                <th scope="col" class="text-right font-weight-bold">Purchase Price</th>
                                <th scope="col" class="text-right font-weight-bold">Purchase Date</th>
                                <th scope="col" class="text-right font-weight-bold">Total Cost</th>
                                <th scope="col" class="text-right font-weight-bold">MarketValue</th>
                                <th scope="col" class="text-right font-weight-bold">Gain</th>
                                <th scope="col" class="text-right font-weight-bold">Day's Gain</th>
                                <th scope="col" class="text-right font-weight-bold">Return</th>
                                <th scope="col" class="text-right font-weight-bold"></th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var stock in Model.Stocks)
                            {

                                <tr>
                                    <th class="d-none" id="@stock.PlayerStockId"></th>
                                    <th scope="row" class="font-weight-bold">@stock.Symbol</th>
                                    <td class="font-weight-bold">@stock.Name</td>
                                    <td class="text-right">@stock.CurrentPrice.ToString("c")</td>
                                    <td class="@(stock.Change < 0 ? "text-right text-danger font-weight-bold" : "text-right text-success font-weight-bold")">@stock.Change.ToString("0.00")</td>
                                    <td class="@(stock.PercentChange < 0 ? "text-right text-danger font-weight-bold" : "text-right text-success font-weight-bold")">@stock.PercentChange.ToString("p")</td>
                                    <td class="text-right">@stock.Shares</td>
                                    <td class="text-right">@stock.PurchasePrice.ToString("c")</td>
                                    <td class="text-right">@stock.PurchaseDate</td>
                                    <td class="text-right">@stock.TotalCost.ToString("c")</td>
                                    <td class="text-right">@stock.MarketValue.ToString("c")</td>
                                    <td class="@(stock.Gain < 0 ? "text-right text-danger font-weight-bold" : "text-right")">@stock.Gain.ToString("c")</td>
                                    <td class="@(stock.TodaysGain < 0 ? "text-right text-danger font-weight-bold" : "text-right")">@stock.TodaysGain.ToString("c")</td>
                                    <td class="@(stock.Return < 0 ? "text-right text-danger font-weight-bold" : "text-right")">@stock.Return.ToString("p")</td>
                                    <td>
                                        <form asp-action="sell" method="post" id="sell-form">
                                            <input type="hidden" name="stockId" value="@stock.PlayerStockId" />
                                            <input type="hidden" name="value" value="@stock.MarketValue" />
                                            <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#">Sell</button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    }
                    else
                    {
                        <thead>
                            <tr scope="row" class="font-weight-bold">
                                <th>Symbol</th>
                                <th>Name</th>
                                <th scope="col" class="text-right font-weight-bold">Price</th>
                                <th scope="col" class="text-right font-weight-bold">Change</th>
                                <th scope="col" class="text-right font-weight-bold">% Change</th>
                                <th scope="col" class="text-right font-weight-bold">Shares</th>
                                <th scope="col" class="text-right font-weight-bold">Purchase Price</th>
                                <th scope="col" class="text-right font-weight-bold">Purchase Date</th>
                                <th scope="col" class="text-right font-weight-bold">Total Cost</th>
                                <th scope="col" class="text-right font-weight-bold">MarketValue</th>
                                <th scope="col" class="text-right font-weight-bold">Gain</th>
                                <th scope="col" class="text-right font-weight-bold">Day's Gain</th>
                                <th scope="col" class="text-right font-weight-bold">Return</th>
                                <th scope="col" class="text-right font-weight-bold"></th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th class="d-none" id="null"></th>
                                <th scope="row" class="font-weight-bold"></th>
                                <td class="font-weight-bold"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                            </tr>
                        </tbody>
                    }
                </table>
            </div>
        </div>
    </div>

<div id="confirmSale-modal" class="modal fade row" tabindex="-1" role="dialog" aria-labelledby="confirmSale-modal-lbl" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h3 id="confirmSale-modal-lbl">Please Confirm</h3>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col">
                            <p class="font-weight-bold">Are you sure?</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button type="button" class="btn btn-success" onclick="Sell()">Submit</button>
            </div>
        </div>
    </div>
</div>