Models/Entity/QuestionType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ThatsLife.Models.Entity
{
    public class QuestionType : BaseEntity 
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

    }
}

Models/Questions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ThatsLife.Models
{
    public class Questions
    {
        public TriviaQuestion[] Results { get; set; }
    }

    public class TriviaQuestion
    {
        public string Category { get; set; }
        public string Type { get; set; }
        public string Difficulty { get; set; }
        public string Question { get; set; }
        public string Correct_answer { get; set; }
        public string[] Incorrect_answers { get; set; }
        public string Selected { get; set; }
        public string [] Choices 
        {
            
            //Randomizes the choices so the answers are always in same spot
            get
            {
                string[] selection;
                if(Type == "boolean")
                {
                    selection = new string[2];
                    selection[0] = "True";
                    selection[1] = "False";
                }
                else
                {
                    selection = new string[4];
                    Array.Copy(Incorrect_answers, selection, Incorrect_answers.Length);
                    selection[3] = Correct_answer;
                    Random rand = new Random();

                    for (int i = 0; i < selection.Length - 1; i++)
                    {
                        int j = rand.Next(i, selection.Length);
                        string temp = selection[i];
                        selection[i] = selection[j];
                        selection[j] = temp;
                    }
                }
                
                return selection;
            }
            set
            {
            }
        }
    }



}

Controllers/TriviaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using ThatsLife.Models.DAL;
using ThatsLife.Models.Entity;
using ThatsLife.Models.ViewModels;
using System.Linq;
using Newtonsoft.Json;
using System.Threading.Tasks;
using ThatsLife.Models;
using Newtonsoft.Json.Linq;
using System.Configuration;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ThatsLife.Controllers
{
    
    [Authorize]
    public class TriviaController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly IRepository<PlayerProfile> _profileRepository;
        private readonly IRepository<Category> _categoryRepository;
        private readonly IRepository<Difficulty> _difficultyRepository;
        private readonly IRepository<QuestionType> _questionTypeRepository;
        private readonly IRepository<PlayerQuiz> _quizRepository;
        private readonly IRepository<PlayerCash> _cashRepository;
        private readonly IRepository<PlayerPrestigeScore> _prestigeScoreRepository;
        private readonly IRepository<PlayerTransaction> _transactionRepository;

        public TriviaController(UserManager<IdentityUser> userManager,
            IRepository<PlayerProfile> profileRepository,
        IRepository<Category> categoryRepository,
        IRepository<Difficulty> difficultyRepository,
        IRepository<QuestionType> questionTypeRepository,
        IRepository<PlayerQuiz> quizRepository,
        IRepository<PlayerTransaction> transactionRepository,
        IRepository<PlayerPrestigeScore> prestigeScoreRepository,
        IRepository<PlayerCash> cashRepository
        )
        {
            _userManager = userManager;
            _profileRepository = profileRepository;
            _categoryRepository = categoryRepository;
            _difficultyRepository = difficultyRepository;
            _questionTypeRepository = questionTypeRepository;
            _quizRepository = quizRepository;
            _transactionRepository = transactionRepository;
            _cashRepository = cashRepository;
            _prestigeScoreRepository = prestigeScoreRepository;
        }

    
        
        public IActionResult Parameters()
        {
            TriviaParametersViewModel triviaParametersViewModel = new TriviaParametersViewModel();


            triviaParametersViewModel.Categories = _categoryRepository.FindAll().ToList().Select(c => new SelectListItem
            {
                Value = c.TriviaDbCategoryId.ToString(),
                Text = c.Name
            });
            triviaParametersViewModel.Difficulies = _difficultyRepository.FindAll().ToList().Select(c => new SelectListItem
            {
                Value = c.Name.ToLower(),
                Text = c.Name
            }) ;
            triviaParametersViewModel.TypeList = _questionTypeRepository.FindAll().ToList().Select(c => new SelectListItem
            {
                Value = c.Name == "Multiple Choice"? "multiple" : "boolean",
                Text = c.Name
            });

            return View(triviaParametersViewModel);
        }

         public async Task<IActionResult> QuestionsAsync(TriviaParametersViewModel triviaParameters)
        {

            int categoryId = triviaParameters.CategoryId;
            string difficulty = triviaParameters.Difficulty;
            string questionType = triviaParameters.QuestionType;
            int amount = triviaParameters.NumberOfQuestions;

            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Ignore
            };

            string sessionToken = HttpContext.Session.GetString("ApiSessionToken");
            if ( sessionToken == null)
            {
                string tokenRequestUrl = @"https://opentdb.com/api_token.php?command=request";
                var jsonResponse = await ApiHub.GetJson(tokenRequestUrl);
                var resultJToken = JsonConvert.DeserializeObject<JToken>(jsonResponse);
                var apiSessionToken = resultJToken["token"].ToString();
                HttpContext.Session.SetString("ApiSessionToken", apiSessionToken);
                sessionToken = apiSessionToken;


            }
            string url = $@"https://opentdb.com/api.php?amount={amount}&category={categoryId}&difficulty={difficulty}&type={questionType}&token={sessionToken}";
            var json = await ApiHub.GetJson(url);

            var result = JsonConvert.DeserializeObject<Questions>(json);
            TriviaQuestionsViewModel triviaQuestionsViewModel = new TriviaQuestionsViewModel();
            triviaQuestionsViewModel.Questions = result;

            return View("questions",triviaQuestionsViewModel);
        }

        public IActionResult Performance()
        {
            var triviaPerformanceViewModel = new TriviaPerformanceViewModel();
            var userId = _userManager.GetUserId(User);
            PlayerProfile player = _profileRepository.FindByCondition(p => p.UserId == userId).First();
            triviaPerformanceViewModel.Quizes = _quizRepository.FindByCondition(p => p.Player == player);
            int totalCorrect = triviaPerformanceViewModel.Quizes.Select(q => q.Correct).Sum();
            int totalAttempted = triviaPerformanceViewModel.Quizes.Select(q => q.Attempted).Sum();
            triviaPerformanceViewModel.TotalAttempted = totalAttempted;
            triviaPerformanceViewModel.TotalCorrect = totalCorrect;
            triviaPerformanceViewModel.TotalIncorrect = totalAttempted - totalCorrect;

            return View(triviaPerformanceViewModel);
        }

        public IActionResult Results(TriviaQuestionsViewModel triviaQuestionsViewModel)
        {
            TriviaQuestionsViewModel t = triviaQuestionsViewModel;
            string difficultySelect = t.Questions.Results.First().Difficulty;
            string categorySelect = t.Questions.Results.First().Category;
            string typeSelect = t.Questions.Results.First().Type == "multiple" ? "Multiple Choice" : "True/False";


            var userId = _userManager.GetUserId(User);
            PlayerProfile player = _profileRepository.FindByCondition(p => p.UserId == userId).First();
            Difficulty difficulty = _difficultyRepository.FindByCondition(q => q.Name == difficultySelect).First();
            Category category = _categoryRepository.FindByCondition(q => q.Name == categorySelect).First();
            QuestionType type = _questionTypeRepository.FindByCondition(q => q.Name == typeSelect).First();


            //Adds Entry to Player's quizes
            PlayerQuiz quiz = new PlayerQuiz();
            quiz.Player = player;
            quiz.Difficulty = difficulty;
            quiz.QuestionType = type;
            quiz.Category = category;
            quiz.Attempted = t.Questions.Results.Select(q => q.Selected).Count();
            quiz.Correct = t.Questions.Results.Where(q => q.Selected == "true").Count();
            _quizRepository.Create(quiz);



            //Adds Entry into Players Cash account
            PlayerCash playerCash = new PlayerCash();
            playerCash.ProfileId = player.Id;
            int multiplier = 0;
            switch (difficultySelect)
            {
                case "easy":
                    multiplier += quiz.Correct * (typeSelect == "Multiple Choice" ? 2 : 1);
                    break;
                case "medium":
                    multiplier += quiz.Correct * (typeSelect == "Multiple Choice" ? 2 : 1) * 2;
                    break;
                case "hard":
                    multiplier += quiz.Correct * (typeSelect == "Multiple Choice" ? 2 : 1) * 3;
                    break;
            }

            playerCash.Balance = _cashRepository
               .FindByCondition(p => p.ProfileId == player.Id)
               .OrderByDescending(c => c.CreatedDate)
               .Select(p => p.Balance)
               .FirstOrDefault();
            playerCash.Balance += (multiplier * 10);
            _cashRepository.Create(playerCash);


            //Adds Entry to Players Transactions
            PlayerTransaction playerTransaction = new PlayerTransaction();
            playerTransaction.ProfileId = player.Id;
            playerTransaction.TransactionType = "Trivia";
            playerTransaction.TransactionDescription = $"{quiz.Correct} ,{difficultySelect}, {typeSelect} questions";
            playerTransaction.Price = multiplier * 10;
            _transactionRepository.Create(playerTransaction);


            //Adds Entry to Players Prestige Score
            PlayerPrestigeScore playerPrestige = new PlayerPrestigeScore();
            playerPrestige.ProfileId = player.Id;
            playerPrestige.Source = "Knowledge Reward";
            playerPrestige.Score = _prestigeScoreRepository
            .FindByCondition(p => p.ProfileId == player.Id)
            .OrderByDescending(c => c.CreatedDate)
            .Select(p => p.Score)
            .FirstOrDefault();
            playerPrestige.Score += multiplier * 10;
            playerPrestige.PointsEarned = multiplier * 10;
            _prestigeScoreRepository.Create(playerPrestige);




            return RedirectToAction("Performance");
        }
       
        

    }
}

Views/Trivia/Components/TriviaOverall/TriviaOverallViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ThatsLife.Models.DAL;
using ThatsLife.Models.Entity;
using Microsoft.AspNetCore.Http;
using ThatsLife.Models;
using Newtonsoft.Json;
using ThatsLife.Models.ViewModels;

namespace ThatsLife.Views.Trivia.Components.TriviaOverall
{
    public class TriviaOverallViewComponent : ViewComponent
    {
        private readonly IRepository<PlayerQuiz> _quizRepository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IRepository<PlayerProfile> _profileRepository;

        public TriviaOverallViewComponent(IRepository<PlayerQuiz> quizRepository,
            UserManager<IdentityUser> userManager,
            IRepository<PlayerProfile> profileRepository)
        {
            _quizRepository = quizRepository;
            _userManager = userManager;
            _profileRepository = profileRepository;
        }
        
        public IViewComponentResult Invoke()

        {
            var userId = _userManager.GetUserId(Request.HttpContext.User);
            PlayerProfile player = _profileRepository.FindByCondition(p => p.UserId == userId).First();

            int correct = _quizRepository.FindByCondition(p => p.Player == player).Select(c => c.Correct).Sum();
            int attempted = _quizRepository.FindByCondition(p => p.Player == player).Select(c => c.Attempted).Sum();
            int incorrect = attempted - correct;

            var chartData = @"
            {
                type: 'pie',
                responsive: true,
                data:
                {
                    labels: ['Correct','Incorrect'],
                    datasets: [{
                        label: 'Overall Trivia Performance',
                        data: [" + correct + "," + incorrect + "]," +
                        "backgroundColor: [ 'rgba(144,238,144, 0.3)', 'rgba(255,114,111,0.3)']," +
                        "hoverOffset:4"+
                    "}]"+
                "}" +
            "}";

            var chart = JsonConvert.DeserializeObject<TriviaOverallChart>(chartData);
            var chartModel = new OverallChartViewModel
            {
                Chart = chart,
                ChartJson = JsonConvert.SerializeObject(chart, new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore
                })
            };

            return View(chartModel);
        }
    }
}

Views/Trivia/Parameters.cshtml
@model ThatsLife.Models.ViewModels.TriviaParametersViewModel



<div class="container-fluid">
    <div class="row">
        
        <div class="col-4 offset-1 mt-5 ">
            <h3 class="my-5">Make your selection to begin your quiz</h3>
            <form asp-action="questions">
                <div class="form-group">
                    <input type="text" name="NumberOfQuestions" id="NumberOfQuestions" class="form-control form-control-lg mb-5" placeholder="Number of Questions [1-50]" />
                    <select asp-for="CategoryId" asp-items="@Model.Categories" class="form-control form-control-lg mb-5">
                        <option>Category</option>
                    </select>
                    <select asp-for="Difficulty" asp-items="@Model.Difficulies" class="form-control form-control-lg mb-5">
                        <option>Difficulty</option>
                    </select>
                    <select asp-for="QuestionType" asp-items="@Model.TypeList" class="form-control form-control-lg">
                        <option>Type</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary btn-lg mt-5">Begin Quiz</button>
            </form>

        </div>
        <div class="col-4 ml-5 ">
            <div class="h1 my-5">
                Earn Virtual Currency By Answering Questions!
            </div>
            <div class="trivia-param">
                The objective is to earn cash to continue investing.  There are various categories to choose from.  There are three levels of difficulty (easy, medium, hard).  There are two types of questions (multiple choice, or true/false).  For multiple choice there are four choices.
            </div>
            <div class="ml-2 index-text">
                <div class="mt-5 font-weight-bold">
                    Total earned = $10 for every queston x  level of difficulty.  Multiple Choice earns you double.
                </div>
                 <div class="">
                    <div>
                        Example1: 10 easy multiple choice questions = $10 x 1 x 2 = $200
                    </div>
                    <div class="mb-5">
                        Example2: 10 hard true/false questions = $10 x 3  = $300
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Trivia/Performance.cshtml
@model ThatsLife.Models.ViewModels.TriviaPerformanceViewModel;

<div class="row border shadow m-2 w-100 p-4">
    <div class="col ml-5"> @await Component.InvokeAsync("TriviaOverall")</div>
    <div class="col align-self-center">
        @{ 
            var percentCorrect =  Model.TotalAttempted == 0 ? 0.0 : Model.TotalCorrect / (double)Model.TotalAttempted;
                <div class="h3">
                    Overall Performance : @percentCorrect.ToString("p")
                </div>
        <div>
            <span>Total Correct: @Model.TotalCorrect</span>
            <span></span>
        </div>
        <div>
            <span>Total Incorrect: </span>@Model.TotalIncorrect
        </div>
        }
    </div>
    
</div>

<div class=" row border shadow m-2 w-100 p-3">

    <div class="col">
        <div><p class="pb-4 h1">Past Quizes<p></div>
        <div class="table-responsive-sm">
            <table class="table table-striped">
                <thead>
                    <tr scope="row" class="font-weight-bold">
                        <th scope="col">Date Taken</th>
                        <th scope="col">Attempted</th>
                        <th scope="col">Incorrect</th>
                        <th scope="col">Correct</th>
                        <th scope="col">Percent Correct</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var quiz in Model.Quizes)
                    {
                        var percentage = quiz.Attempted == 0 ? 0.0 : (quiz.Correct / (double)quiz.Attempted);
                        <tr>
                            <th scope="row">@quiz.CreatedDate</th>
                            <td>@quiz.Attempted</td>
                            <td>@(quiz.Attempted - quiz.Correct)</td>
                            <td>@quiz.Correct</td>
                            <td>@percentage.ToString("p")</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Trivia/Questions.cshtml
@model ThatsLife.Models.ViewModels.TriviaQuestionsViewModel;
@{ if (!Model.Questions.Results.Any())
    {
         <div class="row">
            <div class="col border shadow m-5 p-5">

                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-exclamation fa-lg text-info m-5" style="font-size:36px;"></i>Sorry</h5>
                    <p class="card-text">Questions are obtained from TriviaDB and there currently are not questions that meet your critera.</p>
                    <a asp-action="parameters" class="btn btn-primary">Go Back</a>
                </div>
            </div>
        </div>
    }
    else
    {
        var category = "";
        var difficulty = "";
        var type = "";
        <form asp-controller="trivia" asp-action="results" class="m-5 pl-2">
            @{
                int questionNumber = 1;
                foreach (var item in Model.Questions.Results)
                {
                    difficulty = item.Difficulty;
                    category = item.Category;
                    type = item.Type;

                    <input type="hidden" asp-for="@Model.Questions.Results[questionNumber-1].Category" value="@category" />
                    <input type="hidden" asp-for="@Model.Questions.Results[questionNumber-1].Difficulty" value="@difficulty" />
                    <input type="hidden" asp-for="@Model.Questions.Results[questionNumber-1].Type" id="type" value="@type" />

                    <div class="mt-5">

                        <div class="mb-3"><span class="pr-4">@questionNumber.</span>@System.Net.WebUtility.HtmlDecode(@item.Question) </div>

                        @{
                            int choiceNumber = 0;
                            foreach (var choice in item.Choices)
                            {
                                <div class="form-check pl-4 py-1">
                                    @if (item.Correct_answer == choice)
                                    {

                                        <input class="ml-2" type="radio" asp-for="@Model.Questions.Results[questionNumber-1].Selected" id="radio-@(questionNumber)-@(choiceNumber)" value="true">
                                        <label class="pl-3">
                                            @System.Net.WebUtility.HtmlDecode(choice)
                                            <i id="icon-@(questionNumber)-@(choiceNumber)" class="d-none ml-5">
                                                <e class="ml-3 font-weight-light">Correct!</e>
                                            </i>
                                        </label>

                                    }
                                    else
                                    {

                                        <input class="ml-2" type="radio" asp-for="@Model.Questions.Results[questionNumber-1].Selected" id="radio-@(questionNumber)-@(choiceNumber)" value="false">
                                        <label class="pl-3">
                                            @System.Net.WebUtility.HtmlDecode(choice)
                                            <i id="icon-@(questionNumber)-@(choiceNumber)" class="d-none ml-5 ">
                                                <e class="ml-3 font-weight-light">Incorrect!</e>
                                            </i>
                                        </label>

                                    }
                                </div>
                                choiceNumber++;
                            }
                        }


                    </div>
                    questionNumber++;
                }
            }

            <button id="submit" type="button" class="btn btn-lg btn-secondary mt-5" onclick="ValidateQuiz()">Submit</button>
            <button id="continue" type="submit" class="btn btn-lg btn-secondary mt-5 d-none">Continue</button>
        </form>
    }
}